### ISSUE TITLE
Firefox Developer Edition default theme name

### ISSUE THREAD

**Issue by zhikiri** [shvaikalesh/detect-theme#1]
When I tried to run script in my <code>Firefox Developer Edition v44.0a2</code> I've received <code>"blue"</code>. 
Is it a correct behaviour ?

**Comment by shvaikalesh** [comment]
> Is it a correct behaviour ?

It depends on your operating system. If you are running OS X and did not change appearance to `"graphite"` in `System Preferences.app` then yes, it is correct.

**Comment by zhikiri** [comment]
Yes, I used OS X for this test and I didn't change the system preferences.
I though name of the default OS X visual theme is <code>Aqua</code>. 
If it's not a bug, sorry for that :) 
Wikipedia link: <a href="https://en.wikipedia.org/wiki/Aqua_(user_interface)" target="_blank"><i>OS X GUI and Visual theme</i></a>
